// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// --------------------------------------------------------------------------------
// Tool Version: Vivado v.2025.1 (lin64) Build 6140274 Wed May 21 22:58:25 MDT 2025
// Date        : Sat Nov  8 01:31:19 2025
// Host        : ssi-fpgaserv running 64-bit Ubuntu 24.04.3 LTS
// Command     : write_verilog -force -mode synth_stub -rename_top xdma_hbm_hbm_0_0 -prefix
//               xdma_hbm_hbm_0_0_ xdma_hbm_hbm_0_0_stub.v
// Design      : xdma_hbm_hbm_0_0
// Purpose     : Stub declaration of top-level module interface
// Device      : xcvu37p-fsvh2892-2L-e
// --------------------------------------------------------------------------------

// This empty module with port declaration file causes synthesis tools to infer a black box for IP.
// The synthesis directives are for Synopsys Synplify support to prevent IO buffer insertion.
// Please paste the declaration into a Verilog source file or add the file as an additional source.
(* CHECK_LICENSE_TYPE = "xdma_hbm_hbm_0_0,hbm_v1_0_17,{}" *) (* CORE_GENERATION_INFO = "xdma_hbm_hbm_0_0,hbm_v1_0_17,{x_ipProduct=Vivado 2025.1,x_ipVendor=xilinx.com,x_ipLibrary=ip,x_ipName=hbm,x_ipVersion=1.0,x_ipCoreRevision=17,x_ipLanguage=VERILOG,x_ipSimLanguage=MIXED,HBM_STACK=1,SWITCH_ENABLE_00=FALSE,SWITCH_ENABLE_01=FALSE,INIT_BYPASS=FALSE,INIT_SEQ_TIMEOUT=10000000,AXI_RST_ASSERT_WIDTH=16,AXI_RST_DEASSERT_WIDTH=2,TEMP_WAIT_PERIOD_0=100000,TEMP_WAIT_PERIOD_1=100000,SWITCH_EN_0=0,SWITCH_EN_1=0,AXI_CLK_FREQ=450,AXI_CLK1_FREQ=450,HBM_REF_CLK_FREQ_0=100,HBM_REF_CLK_FREQ_1=100,HBM_CLK_FREQ_0=500,HBM_CLK_FREQ_1=900,HBM_STACK_NUM=1,CLK_SEL_00=FALSE,CLK_SEL_01=FALSE,CLK_SEL_02=FALSE,CLK_SEL_03=FALSE,CLK_SEL_04=FALSE,CLK_SEL_05=FALSE,CLK_SEL_06=FALSE,CLK_SEL_07=TRUE,CLK_SEL_08=FALSE,CLK_SEL_09=FALSE,CLK_SEL_10=FALSE,CLK_SEL_11=FALSE,CLK_SEL_12=FALSE,CLK_SEL_13=FALSE,CLK_SEL_14=FALSE,CLK_SEL_15=FALSE,CLK_SEL_16=FALSE,CLK_SEL_17=FALSE,CLK_SEL_18=FALSE,CLK_SEL_19=FALSE,CLK_SEL_20=FALSE,CLK_SEL_21=FALSE,CLK_SEL_22=FALSE,CLK_SEL_23=FALSE,CLK_SEL_24=FALSE,CLK_SEL_25=FALSE,CLK_SEL_26=FALSE,CLK_SEL_27=FALSE,CLK_SEL_28=FALSE,CLK_SEL_29=FALSE,CLK_SEL_30=FALSE,CLK_SEL_31=FALSE,DATARATE_STACK_0=1000,DATARATE_STACK_1=1800,READ_PERCENT_00=40,READ_PERCENT_01=40,READ_PERCENT_02=40,READ_PERCENT_03=40,READ_PERCENT_04=40,READ_PERCENT_05=40,READ_PERCENT_06=40,READ_PERCENT_07=40,READ_PERCENT_08=40,READ_PERCENT_09=40,READ_PERCENT_10=40,READ_PERCENT_11=40,READ_PERCENT_12=40,READ_PERCENT_13=40,READ_PERCENT_14=40,READ_PERCENT_15=40,READ_PERCENT_16=40,READ_PERCENT_17=40,READ_PERCENT_18=40,READ_PERCENT_19=40,READ_PERCENT_20=40,READ_PERCENT_21=40,READ_PERCENT_22=40,READ_PERCENT_23=40,READ_PERCENT_24=40,READ_PERCENT_25=40,READ_PERCENT_26=40,READ_PERCENT_27=40,READ_PERCENT_28=40,READ_PERCENT_29=40,READ_PERCENT_30=40,READ_PERCENT_31=40,WRITE_PERCENT_00=40,WRITE_PERCENT_01=40,WRITE_PERCENT_02=40,WRITE_PERCENT_03=40,WRITE_PERCENT_04=40,WRITE_PERCENT_05=40,WRITE_PERCENT_06=40,WRITE_PERCENT_07=40,WRITE_PERCENT_08=40,WRITE_PERCENT_09=40,WRITE_PERCENT_10=40,WRITE_PERCENT_11=40,WRITE_PERCENT_12=40,WRITE_PERCENT_13=40,WRITE_PERCENT_14=40,WRITE_PERCENT_15=40,WRITE_PERCENT_16=40,WRITE_PERCENT_17=40,WRITE_PERCENT_18=40,WRITE_PERCENT_19=40,WRITE_PERCENT_20=40,WRITE_PERCENT_21=40,WRITE_PERCENT_22=40,WRITE_PERCENT_23=40,WRITE_PERCENT_24=40,WRITE_PERCENT_25=40,WRITE_PERCENT_26=40,WRITE_PERCENT_27=40,WRITE_PERCENT_28=40,WRITE_PERCENT_29=40,WRITE_PERCENT_30=40,WRITE_PERCENT_31=40,PAGEHIT_PERCENT_00=75,PAGEHIT_PERCENT_01=75,MC_ENABLE_00=TRUE,MC_ENABLE_01=TRUE,MC_ENABLE_02=TRUE,MC_ENABLE_03=TRUE,MC_ENABLE_04=TRUE,MC_ENABLE_05=TRUE,MC_ENABLE_06=TRUE,MC_ENABLE_07=TRUE,MC_ENABLE_08=FALSE,MC_ENABLE_09=FALSE,MC_ENABLE_10=FALSE,MC_ENABLE_11=FALSE,MC_ENABLE_12=FALSE,MC_ENABLE_13=FALSE,MC_ENABLE_14=FALSE,MC_ENABLE_15=FALSE,MC_ENABLE_APB_00=TRUE,MC_ENABLE_APB_01=FALSE,PHY_ENABLE_00=TRUE,PHY_ENABLE_01=TRUE,PHY_ENABLE_02=TRUE,PHY_ENABLE_03=TRUE,PHY_ENABLE_04=TRUE,PHY_ENABLE_05=TRUE,PHY_ENABLE_06=TRUE,PHY_ENABLE_07=TRUE,PHY_ENABLE_08=TRUE,PHY_ENABLE_09=TRUE,PHY_ENABLE_10=TRUE,PHY_ENABLE_11=TRUE,PHY_ENABLE_12=TRUE,PHY_ENABLE_13=TRUE,PHY_ENABLE_14=TRUE,PHY_ENABLE_15=TRUE,PHY_ENABLE_16=FALSE,PHY_ENABLE_17=FALSE,PHY_ENABLE_18=FALSE,PHY_ENABLE_19=FALSE,PHY_ENABLE_20=FALSE,PHY_ENABLE_21=FALSE,PHY_ENABLE_22=FALSE,PHY_ENABLE_23=FALSE,PHY_ENABLE_24=FALSE,PHY_ENABLE_25=FALSE,PHY_ENABLE_26=FALSE,PHY_ENABLE_27=FALSE,PHY_ENABLE_28=FALSE,PHY_ENABLE_29=FALSE,PHY_ENABLE_30=FALSE,PHY_ENABLE_31=FALSE,PHY_ENABLE_APB_00=TRUE,PHY_ENABLE_APB_01=FALSE}" *) (* DowngradeIPIdentifiedWarnings = "yes" *) 
(* X_CORE_INFO = "hbm_v1_0_17,Vivado 2025.1" *) 
module xdma_hbm_hbm_0_0(HBM_REF_CLK_0, AXI_00_ACLK, AXI_00_ARESET_N, 
  AXI_00_ARADDR, AXI_00_ARBURST, AXI_00_ARID, AXI_00_ARLEN, AXI_00_ARSIZE, AXI_00_ARVALID, 
  AXI_00_AWADDR, AXI_00_AWBURST, AXI_00_AWID, AXI_00_AWLEN, AXI_00_AWSIZE, AXI_00_AWVALID, 
  AXI_00_RREADY, AXI_00_BREADY, AXI_00_WDATA, AXI_00_WLAST, AXI_00_WSTRB, 
  AXI_00_WDATA_PARITY, AXI_00_WVALID, AXI_01_ACLK, AXI_01_ARESET_N, AXI_01_ARADDR, 
  AXI_01_ARBURST, AXI_01_ARID, AXI_01_ARLEN, AXI_01_ARSIZE, AXI_01_ARVALID, AXI_01_AWADDR, 
  AXI_01_AWBURST, AXI_01_AWID, AXI_01_AWLEN, AXI_01_AWSIZE, AXI_01_AWVALID, AXI_01_RREADY, 
  AXI_01_BREADY, AXI_01_WDATA, AXI_01_WLAST, AXI_01_WSTRB, AXI_01_WDATA_PARITY, 
  AXI_01_WVALID, AXI_02_ACLK, AXI_02_ARESET_N, AXI_02_ARADDR, AXI_02_ARBURST, AXI_02_ARID, 
  AXI_02_ARLEN, AXI_02_ARSIZE, AXI_02_ARVALID, AXI_02_AWADDR, AXI_02_AWBURST, AXI_02_AWID, 
  AXI_02_AWLEN, AXI_02_AWSIZE, AXI_02_AWVALID, AXI_02_RREADY, AXI_02_BREADY, AXI_02_WDATA, 
  AXI_02_WLAST, AXI_02_WSTRB, AXI_02_WDATA_PARITY, AXI_02_WVALID, AXI_03_ACLK, 
  AXI_03_ARESET_N, AXI_03_ARADDR, AXI_03_ARBURST, AXI_03_ARID, AXI_03_ARLEN, AXI_03_ARSIZE, 
  AXI_03_ARVALID, AXI_03_AWADDR, AXI_03_AWBURST, AXI_03_AWID, AXI_03_AWLEN, AXI_03_AWSIZE, 
  AXI_03_AWVALID, AXI_03_RREADY, AXI_03_BREADY, AXI_03_WDATA, AXI_03_WLAST, AXI_03_WSTRB, 
  AXI_03_WDATA_PARITY, AXI_03_WVALID, AXI_04_ACLK, AXI_04_ARESET_N, AXI_04_ARADDR, 
  AXI_04_ARBURST, AXI_04_ARID, AXI_04_ARLEN, AXI_04_ARSIZE, AXI_04_ARVALID, AXI_04_AWADDR, 
  AXI_04_AWBURST, AXI_04_AWID, AXI_04_AWLEN, AXI_04_AWSIZE, AXI_04_AWVALID, AXI_04_RREADY, 
  AXI_04_BREADY, AXI_04_WDATA, AXI_04_WLAST, AXI_04_WSTRB, AXI_04_WDATA_PARITY, 
  AXI_04_WVALID, AXI_05_ACLK, AXI_05_ARESET_N, AXI_05_ARADDR, AXI_05_ARBURST, AXI_05_ARID, 
  AXI_05_ARLEN, AXI_05_ARSIZE, AXI_05_ARVALID, AXI_05_AWADDR, AXI_05_AWBURST, AXI_05_AWID, 
  AXI_05_AWLEN, AXI_05_AWSIZE, AXI_05_AWVALID, AXI_05_RREADY, AXI_05_BREADY, AXI_05_WDATA, 
  AXI_05_WLAST, AXI_05_WSTRB, AXI_05_WDATA_PARITY, AXI_05_WVALID, AXI_06_ACLK, 
  AXI_06_ARESET_N, AXI_06_ARADDR, AXI_06_ARBURST, AXI_06_ARID, AXI_06_ARLEN, AXI_06_ARSIZE, 
  AXI_06_ARVALID, AXI_06_AWADDR, AXI_06_AWBURST, AXI_06_AWID, AXI_06_AWLEN, AXI_06_AWSIZE, 
  AXI_06_AWVALID, AXI_06_RREADY, AXI_06_BREADY, AXI_06_WDATA, AXI_06_WLAST, AXI_06_WSTRB, 
  AXI_06_WDATA_PARITY, AXI_06_WVALID, AXI_07_ACLK, AXI_07_ARESET_N, AXI_07_ARADDR, 
  AXI_07_ARBURST, AXI_07_ARID, AXI_07_ARLEN, AXI_07_ARSIZE, AXI_07_ARVALID, AXI_07_AWADDR, 
  AXI_07_AWBURST, AXI_07_AWID, AXI_07_AWLEN, AXI_07_AWSIZE, AXI_07_AWVALID, AXI_07_RREADY, 
  AXI_07_BREADY, AXI_07_WDATA, AXI_07_WLAST, AXI_07_WSTRB, AXI_07_WDATA_PARITY, 
  AXI_07_WVALID, AXI_08_ACLK, AXI_08_ARESET_N, AXI_08_ARADDR, AXI_08_ARBURST, AXI_08_ARID, 
  AXI_08_ARLEN, AXI_08_ARSIZE, AXI_08_ARVALID, AXI_08_AWADDR, AXI_08_AWBURST, AXI_08_AWID, 
  AXI_08_AWLEN, AXI_08_AWSIZE, AXI_08_AWVALID, AXI_08_RREADY, AXI_08_BREADY, AXI_08_WDATA, 
  AXI_08_WLAST, AXI_08_WSTRB, AXI_08_WDATA_PARITY, AXI_08_WVALID, AXI_09_ACLK, 
  AXI_09_ARESET_N, AXI_09_ARADDR, AXI_09_ARBURST, AXI_09_ARID, AXI_09_ARLEN, AXI_09_ARSIZE, 
  AXI_09_ARVALID, AXI_09_AWADDR, AXI_09_AWBURST, AXI_09_AWID, AXI_09_AWLEN, AXI_09_AWSIZE, 
  AXI_09_AWVALID, AXI_09_RREADY, AXI_09_BREADY, AXI_09_WDATA, AXI_09_WLAST, AXI_09_WSTRB, 
  AXI_09_WDATA_PARITY, AXI_09_WVALID, AXI_10_ACLK, AXI_10_ARESET_N, AXI_10_ARADDR, 
  AXI_10_ARBURST, AXI_10_ARID, AXI_10_ARLEN, AXI_10_ARSIZE, AXI_10_ARVALID, AXI_10_AWADDR, 
  AXI_10_AWBURST, AXI_10_AWID, AXI_10_AWLEN, AXI_10_AWSIZE, AXI_10_AWVALID, AXI_10_RREADY, 
  AXI_10_BREADY, AXI_10_WDATA, AXI_10_WLAST, AXI_10_WSTRB, AXI_10_WDATA_PARITY, 
  AXI_10_WVALID, AXI_11_ACLK, AXI_11_ARESET_N, AXI_11_ARADDR, AXI_11_ARBURST, AXI_11_ARID, 
  AXI_11_ARLEN, AXI_11_ARSIZE, AXI_11_ARVALID, AXI_11_AWADDR, AXI_11_AWBURST, AXI_11_AWID, 
  AXI_11_AWLEN, AXI_11_AWSIZE, AXI_11_AWVALID, AXI_11_RREADY, AXI_11_BREADY, AXI_11_WDATA, 
  AXI_11_WLAST, AXI_11_WSTRB, AXI_11_WDATA_PARITY, AXI_11_WVALID, AXI_12_ACLK, 
  AXI_12_ARESET_N, AXI_12_ARADDR, AXI_12_ARBURST, AXI_12_ARID, AXI_12_ARLEN, AXI_12_ARSIZE, 
  AXI_12_ARVALID, AXI_12_AWADDR, AXI_12_AWBURST, AXI_12_AWID, AXI_12_AWLEN, AXI_12_AWSIZE, 
  AXI_12_AWVALID, AXI_12_RREADY, AXI_12_BREADY, AXI_12_WDATA, AXI_12_WLAST, AXI_12_WSTRB, 
  AXI_12_WDATA_PARITY, AXI_12_WVALID, AXI_13_ACLK, AXI_13_ARESET_N, AXI_13_ARADDR, 
  AXI_13_ARBURST, AXI_13_ARID, AXI_13_ARLEN, AXI_13_ARSIZE, AXI_13_ARVALID, AXI_13_AWADDR, 
  AXI_13_AWBURST, AXI_13_AWID, AXI_13_AWLEN, AXI_13_AWSIZE, AXI_13_AWVALID, AXI_13_RREADY, 
  AXI_13_BREADY, AXI_13_WDATA, AXI_13_WLAST, AXI_13_WSTRB, AXI_13_WDATA_PARITY, 
  AXI_13_WVALID, AXI_14_ACLK, AXI_14_ARESET_N, AXI_14_ARADDR, AXI_14_ARBURST, AXI_14_ARID, 
  AXI_14_ARLEN, AXI_14_ARSIZE, AXI_14_ARVALID, AXI_14_AWADDR, AXI_14_AWBURST, AXI_14_AWID, 
  AXI_14_AWLEN, AXI_14_AWSIZE, AXI_14_AWVALID, AXI_14_RREADY, AXI_14_BREADY, AXI_14_WDATA, 
  AXI_14_WLAST, AXI_14_WSTRB, AXI_14_WDATA_PARITY, AXI_14_WVALID, AXI_15_ACLK, 
  AXI_15_ARESET_N, AXI_15_ARADDR, AXI_15_ARBURST, AXI_15_ARID, AXI_15_ARLEN, AXI_15_ARSIZE, 
  AXI_15_ARVALID, AXI_15_AWADDR, AXI_15_AWBURST, AXI_15_AWID, AXI_15_AWLEN, AXI_15_AWSIZE, 
  AXI_15_AWVALID, AXI_15_RREADY, AXI_15_BREADY, AXI_15_WDATA, AXI_15_WLAST, AXI_15_WSTRB, 
  AXI_15_WDATA_PARITY, AXI_15_WVALID, APB_0_PCLK, APB_0_PRESET_N, AXI_00_ARREADY, 
  AXI_00_AWREADY, AXI_00_RDATA_PARITY, AXI_00_RDATA, AXI_00_RID, AXI_00_RLAST, AXI_00_RRESP, 
  AXI_00_RVALID, AXI_00_WREADY, AXI_00_BID, AXI_00_BRESP, AXI_00_BVALID, AXI_01_ARREADY, 
  AXI_01_AWREADY, AXI_01_RDATA_PARITY, AXI_01_RDATA, AXI_01_RID, AXI_01_RLAST, AXI_01_RRESP, 
  AXI_01_RVALID, AXI_01_WREADY, AXI_01_BID, AXI_01_BRESP, AXI_01_BVALID, AXI_02_ARREADY, 
  AXI_02_AWREADY, AXI_02_RDATA_PARITY, AXI_02_RDATA, AXI_02_RID, AXI_02_RLAST, AXI_02_RRESP, 
  AXI_02_RVALID, AXI_02_WREADY, AXI_02_BID, AXI_02_BRESP, AXI_02_BVALID, AXI_03_ARREADY, 
  AXI_03_AWREADY, AXI_03_RDATA_PARITY, AXI_03_RDATA, AXI_03_RID, AXI_03_RLAST, AXI_03_RRESP, 
  AXI_03_RVALID, AXI_03_WREADY, AXI_03_BID, AXI_03_BRESP, AXI_03_BVALID, AXI_04_ARREADY, 
  AXI_04_AWREADY, AXI_04_RDATA_PARITY, AXI_04_RDATA, AXI_04_RID, AXI_04_RLAST, AXI_04_RRESP, 
  AXI_04_RVALID, AXI_04_WREADY, AXI_04_BID, AXI_04_BRESP, AXI_04_BVALID, AXI_05_ARREADY, 
  AXI_05_AWREADY, AXI_05_RDATA_PARITY, AXI_05_RDATA, AXI_05_RID, AXI_05_RLAST, AXI_05_RRESP, 
  AXI_05_RVALID, AXI_05_WREADY, AXI_05_BID, AXI_05_BRESP, AXI_05_BVALID, AXI_06_ARREADY, 
  AXI_06_AWREADY, AXI_06_RDATA_PARITY, AXI_06_RDATA, AXI_06_RID, AXI_06_RLAST, AXI_06_RRESP, 
  AXI_06_RVALID, AXI_06_WREADY, AXI_06_BID, AXI_06_BRESP, AXI_06_BVALID, AXI_07_ARREADY, 
  AXI_07_AWREADY, AXI_07_RDATA_PARITY, AXI_07_RDATA, AXI_07_RID, AXI_07_RLAST, AXI_07_RRESP, 
  AXI_07_RVALID, AXI_07_WREADY, AXI_07_BID, AXI_07_BRESP, AXI_07_BVALID, AXI_08_ARREADY, 
  AXI_08_AWREADY, AXI_08_RDATA_PARITY, AXI_08_RDATA, AXI_08_RID, AXI_08_RLAST, AXI_08_RRESP, 
  AXI_08_RVALID, AXI_08_WREADY, AXI_08_BID, AXI_08_BRESP, AXI_08_BVALID, AXI_09_ARREADY, 
  AXI_09_AWREADY, AXI_09_RDATA_PARITY, AXI_09_RDATA, AXI_09_RID, AXI_09_RLAST, AXI_09_RRESP, 
  AXI_09_RVALID, AXI_09_WREADY, AXI_09_BID, AXI_09_BRESP, AXI_09_BVALID, AXI_10_ARREADY, 
  AXI_10_AWREADY, AXI_10_RDATA_PARITY, AXI_10_RDATA, AXI_10_RID, AXI_10_RLAST, AXI_10_RRESP, 
  AXI_10_RVALID, AXI_10_WREADY, AXI_10_BID, AXI_10_BRESP, AXI_10_BVALID, AXI_11_ARREADY, 
  AXI_11_AWREADY, AXI_11_RDATA_PARITY, AXI_11_RDATA, AXI_11_RID, AXI_11_RLAST, AXI_11_RRESP, 
  AXI_11_RVALID, AXI_11_WREADY, AXI_11_BID, AXI_11_BRESP, AXI_11_BVALID, AXI_12_ARREADY, 
  AXI_12_AWREADY, AXI_12_RDATA_PARITY, AXI_12_RDATA, AXI_12_RID, AXI_12_RLAST, AXI_12_RRESP, 
  AXI_12_RVALID, AXI_12_WREADY, AXI_12_BID, AXI_12_BRESP, AXI_12_BVALID, AXI_13_ARREADY, 
  AXI_13_AWREADY, AXI_13_RDATA_PARITY, AXI_13_RDATA, AXI_13_RID, AXI_13_RLAST, AXI_13_RRESP, 
  AXI_13_RVALID, AXI_13_WREADY, AXI_13_BID, AXI_13_BRESP, AXI_13_BVALID, AXI_14_ARREADY, 
  AXI_14_AWREADY, AXI_14_RDATA_PARITY, AXI_14_RDATA, AXI_14_RID, AXI_14_RLAST, AXI_14_RRESP, 
  AXI_14_RVALID, AXI_14_WREADY, AXI_14_BID, AXI_14_BRESP, AXI_14_BVALID, AXI_15_ARREADY, 
  AXI_15_AWREADY, AXI_15_RDATA_PARITY, AXI_15_RDATA, AXI_15_RID, AXI_15_RLAST, AXI_15_RRESP, 
  AXI_15_RVALID, AXI_15_WREADY, AXI_15_BID, AXI_15_BRESP, AXI_15_BVALID, apb_complete_0, 
  DRAM_0_STAT_CATTRIP, DRAM_0_STAT_TEMP)
/* synthesis syn_black_box black_box_pad_pin="HBM_REF_CLK_0,AXI_00_ARESET_N,AXI_00_ARADDR[32:0],AXI_00_ARBURST[1:0],AXI_00_ARID[5:0],AXI_00_ARLEN[3:0],AXI_00_ARSIZE[2:0],AXI_00_ARVALID,AXI_00_AWADDR[32:0],AXI_00_AWBURST[1:0],AXI_00_AWID[5:0],AXI_00_AWLEN[3:0],AXI_00_AWSIZE[2:0],AXI_00_AWVALID,AXI_00_RREADY,AXI_00_BREADY,AXI_00_WDATA[255:0],AXI_00_WLAST,AXI_00_WSTRB[31:0],AXI_00_WDATA_PARITY[31:0],AXI_00_WVALID,AXI_01_ARESET_N,AXI_01_ARADDR[32:0],AXI_01_ARBURST[1:0],AXI_01_ARID[5:0],AXI_01_ARLEN[3:0],AXI_01_ARSIZE[2:0],AXI_01_ARVALID,AXI_01_AWADDR[32:0],AXI_01_AWBURST[1:0],AXI_01_AWID[5:0],AXI_01_AWLEN[3:0],AXI_01_AWSIZE[2:0],AXI_01_AWVALID,AXI_01_RREADY,AXI_01_BREADY,AXI_01_WDATA[255:0],AXI_01_WLAST,AXI_01_WSTRB[31:0],AXI_01_WDATA_PARITY[31:0],AXI_01_WVALID,AXI_02_ARESET_N,AXI_02_ARADDR[32:0],AXI_02_ARBURST[1:0],AXI_02_ARID[5:0],AXI_02_ARLEN[3:0],AXI_02_ARSIZE[2:0],AXI_02_ARVALID,AXI_02_AWADDR[32:0],AXI_02_AWBURST[1:0],AXI_02_AWID[5:0],AXI_02_AWLEN[3:0],AXI_02_AWSIZE[2:0],AXI_02_AWVALID,AXI_02_RREADY,AXI_02_BREADY,AXI_02_WDATA[255:0],AXI_02_WLAST,AXI_02_WSTRB[31:0],AXI_02_WDATA_PARITY[31:0],AXI_02_WVALID,AXI_03_ARESET_N,AXI_03_ARADDR[32:0],AXI_03_ARBURST[1:0],AXI_03_ARID[5:0],AXI_03_ARLEN[3:0],AXI_03_ARSIZE[2:0],AXI_03_ARVALID,AXI_03_AWADDR[32:0],AXI_03_AWBURST[1:0],AXI_03_AWID[5:0],AXI_03_AWLEN[3:0],AXI_03_AWSIZE[2:0],AXI_03_AWVALID,AXI_03_RREADY,AXI_03_BREADY,AXI_03_WDATA[255:0],AXI_03_WLAST,AXI_03_WSTRB[31:0],AXI_03_WDATA_PARITY[31:0],AXI_03_WVALID,AXI_04_ARESET_N,AXI_04_ARADDR[32:0],AXI_04_ARBURST[1:0],AXI_04_ARID[5:0],AXI_04_ARLEN[3:0],AXI_04_ARSIZE[2:0],AXI_04_ARVALID,AXI_04_AWADDR[32:0],AXI_04_AWBURST[1:0],AXI_04_AWID[5:0],AXI_04_AWLEN[3:0],AXI_04_AWSIZE[2:0],AXI_04_AWVALID,AXI_04_RREADY,AXI_04_BREADY,AXI_04_WDATA[255:0],AXI_04_WLAST,AXI_04_WSTRB[31:0],AXI_04_WDATA_PARITY[31:0],AXI_04_WVALID,AXI_05_ARESET_N,AXI_05_ARADDR[32:0],AXI_05_ARBURST[1:0],AXI_05_ARID[5:0],AXI_05_ARLEN[3:0],AXI_05_ARSIZE[2:0],AXI_05_ARVALID,AXI_05_AWADDR[32:0],AXI_05_AWBURST[1:0],AXI_05_AWID[5:0],AXI_05_AWLEN[3:0],AXI_05_AWSIZE[2:0],AXI_05_AWVALID,AXI_05_RREADY,AXI_05_BREADY,AXI_05_WDATA[255:0],AXI_05_WLAST,AXI_05_WSTRB[31:0],AXI_05_WDATA_PARITY[31:0],AXI_05_WVALID,AXI_06_ARESET_N,AXI_06_ARADDR[32:0],AXI_06_ARBURST[1:0],AXI_06_ARID[5:0],AXI_06_ARLEN[3:0],AXI_06_ARSIZE[2:0],AXI_06_ARVALID,AXI_06_AWADDR[32:0],AXI_06_AWBURST[1:0],AXI_06_AWID[5:0],AXI_06_AWLEN[3:0],AXI_06_AWSIZE[2:0],AXI_06_AWVALID,AXI_06_RREADY,AXI_06_BREADY,AXI_06_WDATA[255:0],AXI_06_WLAST,AXI_06_WSTRB[31:0],AXI_06_WDATA_PARITY[31:0],AXI_06_WVALID,AXI_07_ARESET_N,AXI_07_ARADDR[32:0],AXI_07_ARBURST[1:0],AXI_07_ARID[5:0],AXI_07_ARLEN[3:0],AXI_07_ARSIZE[2:0],AXI_07_ARVALID,AXI_07_AWADDR[32:0],AXI_07_AWBURST[1:0],AXI_07_AWID[5:0],AXI_07_AWLEN[3:0],AXI_07_AWSIZE[2:0],AXI_07_AWVALID,AXI_07_RREADY,AXI_07_BREADY,AXI_07_WDATA[255:0],AXI_07_WLAST,AXI_07_WSTRB[31:0],AXI_07_WDATA_PARITY[31:0],AXI_07_WVALID,AXI_08_ARESET_N,AXI_08_ARADDR[32:0],AXI_08_ARBURST[1:0],AXI_08_ARID[5:0],AXI_08_ARLEN[3:0],AXI_08_ARSIZE[2:0],AXI_08_ARVALID,AXI_08_AWADDR[32:0],AXI_08_AWBURST[1:0],AXI_08_AWID[5:0],AXI_08_AWLEN[3:0],AXI_08_AWSIZE[2:0],AXI_08_AWVALID,AXI_08_RREADY,AXI_08_BREADY,AXI_08_WDATA[255:0],AXI_08_WLAST,AXI_08_WSTRB[31:0],AXI_08_WDATA_PARITY[31:0],AXI_08_WVALID,AXI_09_ARESET_N,AXI_09_ARADDR[32:0],AXI_09_ARBURST[1:0],AXI_09_ARID[5:0],AXI_09_ARLEN[3:0],AXI_09_ARSIZE[2:0],AXI_09_ARVALID,AXI_09_AWADDR[32:0],AXI_09_AWBURST[1:0],AXI_09_AWID[5:0],AXI_09_AWLEN[3:0],AXI_09_AWSIZE[2:0],AXI_09_AWVALID,AXI_09_RREADY,AXI_09_BREADY,AXI_09_WDATA[255:0],AXI_09_WLAST,AXI_09_WSTRB[31:0],AXI_09_WDATA_PARITY[31:0],AXI_09_WVALID,AXI_10_ARESET_N,AXI_10_ARADDR[32:0],AXI_10_ARBURST[1:0],AXI_10_ARID[5:0],AXI_10_ARLEN[3:0],AXI_10_ARSIZE[2:0],AXI_10_ARVALID,AXI_10_AWADDR[32:0],AXI_10_AWBURST[1:0],AXI_10_AWID[5:0],AXI_10_AWLEN[3:0],AXI_10_AWSIZE[2:0],AXI_10_AWVALID,AXI_10_RREADY,AXI_10_BREADY,AXI_10_WDATA[255:0],AXI_10_WLAST,AXI_10_WSTRB[31:0],AXI_10_WDATA_PARITY[31:0],AXI_10_WVALID,AXI_11_ARESET_N,AXI_11_ARADDR[32:0],AXI_11_ARBURST[1:0],AXI_11_ARID[5:0],AXI_11_ARLEN[3:0],AXI_11_ARSIZE[2:0],AXI_11_ARVALID,AXI_11_AWADDR[32:0],AXI_11_AWBURST[1:0],AXI_11_AWID[5:0],AXI_11_AWLEN[3:0],AXI_11_AWSIZE[2:0],AXI_11_AWVALID,AXI_11_RREADY,AXI_11_BREADY,AXI_11_WDATA[255:0],AXI_11_WLAST,AXI_11_WSTRB[31:0],AXI_11_WDATA_PARITY[31:0],AXI_11_WVALID,AXI_12_ARESET_N,AXI_12_ARADDR[32:0],AXI_12_ARBURST[1:0],AXI_12_ARID[5:0],AXI_12_ARLEN[3:0],AXI_12_ARSIZE[2:0],AXI_12_ARVALID,AXI_12_AWADDR[32:0],AXI_12_AWBURST[1:0],AXI_12_AWID[5:0],AXI_12_AWLEN[3:0],AXI_12_AWSIZE[2:0],AXI_12_AWVALID,AXI_12_RREADY,AXI_12_BREADY,AXI_12_WDATA[255:0],AXI_12_WLAST,AXI_12_WSTRB[31:0],AXI_12_WDATA_PARITY[31:0],AXI_12_WVALID,AXI_13_ARESET_N,AXI_13_ARADDR[32:0],AXI_13_ARBURST[1:0],AXI_13_ARID[5:0],AXI_13_ARLEN[3:0],AXI_13_ARSIZE[2:0],AXI_13_ARVALID,AXI_13_AWADDR[32:0],AXI_13_AWBURST[1:0],AXI_13_AWID[5:0],AXI_13_AWLEN[3:0],AXI_13_AWSIZE[2:0],AXI_13_AWVALID,AXI_13_RREADY,AXI_13_BREADY,AXI_13_WDATA[255:0],AXI_13_WLAST,AXI_13_WSTRB[31:0],AXI_13_WDATA_PARITY[31:0],AXI_13_WVALID,AXI_14_ARESET_N,AXI_14_ARADDR[32:0],AXI_14_ARBURST[1:0],AXI_14_ARID[5:0],AXI_14_ARLEN[3:0],AXI_14_ARSIZE[2:0],AXI_14_ARVALID,AXI_14_AWADDR[32:0],AXI_14_AWBURST[1:0],AXI_14_AWID[5:0],AXI_14_AWLEN[3:0],AXI_14_AWSIZE[2:0],AXI_14_AWVALID,AXI_14_RREADY,AXI_14_BREADY,AXI_14_WDATA[255:0],AXI_14_WLAST,AXI_14_WSTRB[31:0],AXI_14_WDATA_PARITY[31:0],AXI_14_WVALID,AXI_15_ARESET_N,AXI_15_ARADDR[32:0],AXI_15_ARBURST[1:0],AXI_15_ARID[5:0],AXI_15_ARLEN[3:0],AXI_15_ARSIZE[2:0],AXI_15_ARVALID,AXI_15_AWADDR[32:0],AXI_15_AWBURST[1:0],AXI_15_AWID[5:0],AXI_15_AWLEN[3:0],AXI_15_AWSIZE[2:0],AXI_15_AWVALID,AXI_15_RREADY,AXI_15_BREADY,AXI_15_WDATA[255:0],AXI_15_WLAST,AXI_15_WSTRB[31:0],AXI_15_WDATA_PARITY[31:0],AXI_15_WVALID,APB_0_PRESET_N,AXI_00_ARREADY,AXI_00_AWREADY,AXI_00_RDATA_PARITY[31:0],AXI_00_RDATA[255:0],AXI_00_RID[5:0],AXI_00_RLAST,AXI_00_RRESP[1:0],AXI_00_RVALID,AXI_00_WREADY,AXI_00_BID[5:0],AXI_00_BRESP[1:0],AXI_00_BVALID,AXI_01_ARREADY,AXI_01_AWREADY,AXI_01_RDATA_PARITY[31:0],AXI_01_RDATA[255:0],AXI_01_RID[5:0],AXI_01_RLAST,AXI_01_RRESP[1:0],AXI_01_RVALID,AXI_01_WREADY,AXI_01_BID[5:0],AXI_01_BRESP[1:0],AXI_01_BVALID,AXI_02_ARREADY,AXI_02_AWREADY,AXI_02_RDATA_PARITY[31:0],AXI_02_RDATA[255:0],AXI_02_RID[5:0],AXI_02_RLAST,AXI_02_RRESP[1:0],AXI_02_RVALID,AXI_02_WREADY,AXI_02_BID[5:0],AXI_02_BRESP[1:0],AXI_02_BVALID,AXI_03_ARREADY,AXI_03_AWREADY,AXI_03_RDATA_PARITY[31:0],AXI_03_RDATA[255:0],AXI_03_RID[5:0],AXI_03_RLAST,AXI_03_RRESP[1:0],AXI_03_RVALID,AXI_03_WREADY,AXI_03_BID[5:0],AXI_03_BRESP[1:0],AXI_03_BVALID,AXI_04_ARREADY,AXI_04_AWREADY,AXI_04_RDATA_PARITY[31:0],AXI_04_RDATA[255:0],AXI_04_RID[5:0],AXI_04_RLAST,AXI_04_RRESP[1:0],AXI_04_RVALID,AXI_04_WREADY,AXI_04_BID[5:0],AXI_04_BRESP[1:0],AXI_04_BVALID,AXI_05_ARREADY,AXI_05_AWREADY,AXI_05_RDATA_PARITY[31:0],AXI_05_RDATA[255:0],AXI_05_RID[5:0],AXI_05_RLAST,AXI_05_RRESP[1:0],AXI_05_RVALID,AXI_05_WREADY,AXI_05_BID[5:0],AXI_05_BRESP[1:0],AXI_05_BVALID,AXI_06_ARREADY,AXI_06_AWREADY,AXI_06_RDATA_PARITY[31:0],AXI_06_RDATA[255:0],AXI_06_RID[5:0],AXI_06_RLAST,AXI_06_RRESP[1:0],AXI_06_RVALID,AXI_06_WREADY,AXI_06_BID[5:0],AXI_06_BRESP[1:0],AXI_06_BVALID,AXI_07_ARREADY,AXI_07_AWREADY,AXI_07_RDATA_PARITY[31:0],AXI_07_RDATA[255:0],AXI_07_RID[5:0],AXI_07_RLAST,AXI_07_RRESP[1:0],AXI_07_RVALID,AXI_07_WREADY,AXI_07_BID[5:0],AXI_07_BRESP[1:0],AXI_07_BVALID,AXI_08_ARREADY,AXI_08_AWREADY,AXI_08_RDATA_PARITY[31:0],AXI_08_RDATA[255:0],AXI_08_RID[5:0],AXI_08_RLAST,AXI_08_RRESP[1:0],AXI_08_RVALID,AXI_08_WREADY,AXI_08_BID[5:0],AXI_08_BRESP[1:0],AXI_08_BVALID,AXI_09_ARREADY,AXI_09_AWREADY,AXI_09_RDATA_PARITY[31:0],AXI_09_RDATA[255:0],AXI_09_RID[5:0],AXI_09_RLAST,AXI_09_RRESP[1:0],AXI_09_RVALID,AXI_09_WREADY,AXI_09_BID[5:0],AXI_09_BRESP[1:0],AXI_09_BVALID,AXI_10_ARREADY,AXI_10_AWREADY,AXI_10_RDATA_PARITY[31:0],AXI_10_RDATA[255:0],AXI_10_RID[5:0],AXI_10_RLAST,AXI_10_RRESP[1:0],AXI_10_RVALID,AXI_10_WREADY,AXI_10_BID[5:0],AXI_10_BRESP[1:0],AXI_10_BVALID,AXI_11_ARREADY,AXI_11_AWREADY,AXI_11_RDATA_PARITY[31:0],AXI_11_RDATA[255:0],AXI_11_RID[5:0],AXI_11_RLAST,AXI_11_RRESP[1:0],AXI_11_RVALID,AXI_11_WREADY,AXI_11_BID[5:0],AXI_11_BRESP[1:0],AXI_11_BVALID,AXI_12_ARREADY,AXI_12_AWREADY,AXI_12_RDATA_PARITY[31:0],AXI_12_RDATA[255:0],AXI_12_RID[5:0],AXI_12_RLAST,AXI_12_RRESP[1:0],AXI_12_RVALID,AXI_12_WREADY,AXI_12_BID[5:0],AXI_12_BRESP[1:0],AXI_12_BVALID,AXI_13_ARREADY,AXI_13_AWREADY,AXI_13_RDATA_PARITY[31:0],AXI_13_RDATA[255:0],AXI_13_RID[5:0],AXI_13_RLAST,AXI_13_RRESP[1:0],AXI_13_RVALID,AXI_13_WREADY,AXI_13_BID[5:0],AXI_13_BRESP[1:0],AXI_13_BVALID,AXI_14_ARREADY,AXI_14_AWREADY,AXI_14_RDATA_PARITY[31:0],AXI_14_RDATA[255:0],AXI_14_RID[5:0],AXI_14_RLAST,AXI_14_RRESP[1:0],AXI_14_RVALID,AXI_14_WREADY,AXI_14_BID[5:0],AXI_14_BRESP[1:0],AXI_14_BVALID,AXI_15_ARREADY,AXI_15_AWREADY,AXI_15_RDATA_PARITY[31:0],AXI_15_RDATA[255:0],AXI_15_RID[5:0],AXI_15_RLAST,AXI_15_RRESP[1:0],AXI_15_RVALID,AXI_15_WREADY,AXI_15_BID[5:0],AXI_15_BRESP[1:0],AXI_15_BVALID,apb_complete_0,DRAM_0_STAT_CATTRIP,DRAM_0_STAT_TEMP[6:0]" */
/* synthesis syn_force_seq_prim="AXI_00_ACLK" */
/* synthesis syn_force_seq_prim="AXI_01_ACLK" */
/* synthesis syn_force_seq_prim="AXI_02_ACLK" */
/* synthesis syn_force_seq_prim="AXI_03_ACLK" */
/* synthesis syn_force_seq_prim="AXI_04_ACLK" */
/* synthesis syn_force_seq_prim="AXI_05_ACLK" */
/* synthesis syn_force_seq_prim="AXI_06_ACLK" */
/* synthesis syn_force_seq_prim="AXI_07_ACLK" */
/* synthesis syn_force_seq_prim="AXI_08_ACLK" */
/* synthesis syn_force_seq_prim="AXI_09_ACLK" */
/* synthesis syn_force_seq_prim="AXI_10_ACLK" */
/* synthesis syn_force_seq_prim="AXI_11_ACLK" */
/* synthesis syn_force_seq_prim="AXI_12_ACLK" */
/* synthesis syn_force_seq_prim="AXI_13_ACLK" */
/* synthesis syn_force_seq_prim="AXI_14_ACLK" */
/* synthesis syn_force_seq_prim="AXI_15_ACLK" */
/* synthesis syn_force_seq_prim="APB_0_PCLK" */;
  (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 HBM_REF_CLK_0 CLK" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME HBM_REF_CLK_0, FREQ_HZ 100000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN xdma_hbm_clk_wiz_0_0_clk_out1, INSERT_VIP 0" *) input HBM_REF_CLK_0;
  (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 ACLK_00_RT CLK" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME ACLK_00_RT, ASSOCIATED_BUSIF SAXI_00_RT, FREQ_HZ 250000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN xdma_hbm_xdma_0_0_axi_aclk, ASSOCIATED_RESET AXI_00_ARESET_N, INSERT_VIP 0" *) input AXI_00_ACLK /* synthesis syn_isclock = 1 */;
  (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 ARST_00_N RST" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME ARST_00_N, POLARITY ACTIVE_LOW, INSERT_VIP 0" *) input AXI_00_ARESET_N;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_00_RT ARADDR" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME SAXI_00_RT, DATA_WIDTH 256, PROTOCOL AXI3, FREQ_HZ 250000000, ID_WIDTH 6, ADDR_WIDTH 33, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 1, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 1, NUM_READ_OUTSTANDING 2, NUM_WRITE_OUTSTANDING 2, MAX_BURST_LENGTH 16, PHASE 0.0, CLK_DOMAIN xdma_hbm_xdma_0_0_axi_aclk, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0" *) input [32:0]AXI_00_ARADDR;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_00_RT ARBURST" *) input [1:0]AXI_00_ARBURST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_00_RT ARID" *) input [5:0]AXI_00_ARID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_00_RT ARLEN" *) input [3:0]AXI_00_ARLEN;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_00_RT ARSIZE" *) input [2:0]AXI_00_ARSIZE;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_00_RT ARVALID" *) input AXI_00_ARVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_00_RT AWADDR" *) input [32:0]AXI_00_AWADDR;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_00_RT AWBURST" *) input [1:0]AXI_00_AWBURST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_00_RT AWID" *) input [5:0]AXI_00_AWID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_00_RT AWLEN" *) input [3:0]AXI_00_AWLEN;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_00_RT AWSIZE" *) input [2:0]AXI_00_AWSIZE;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_00_RT AWVALID" *) input AXI_00_AWVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_00_RT RREADY" *) input AXI_00_RREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_00_RT BREADY" *) input AXI_00_BREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_00_RT WDATA" *) input [255:0]AXI_00_WDATA;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_00_RT WLAST" *) input AXI_00_WLAST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_00_RT WSTRB" *) input [31:0]AXI_00_WSTRB;
  input [31:0]AXI_00_WDATA_PARITY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_00_RT WVALID" *) input AXI_00_WVALID;
  (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 ACLK_01_RT CLK" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME ACLK_01_RT, ASSOCIATED_BUSIF SAXI_01_RT, FREQ_HZ 250000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN xdma_hbm_xdma_0_0_axi_aclk, ASSOCIATED_RESET AXI_01_ARESET_N, INSERT_VIP 0" *) input AXI_01_ACLK /* synthesis syn_isclock = 1 */;
  (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 ARST_01_N RST" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME ARST_01_N, POLARITY ACTIVE_LOW, INSERT_VIP 0" *) input AXI_01_ARESET_N;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_01_RT ARADDR" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME SAXI_01_RT, DATA_WIDTH 256, PROTOCOL AXI3, FREQ_HZ 250000000, ID_WIDTH 6, ADDR_WIDTH 33, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 1, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 1, NUM_READ_OUTSTANDING 2, NUM_WRITE_OUTSTANDING 2, MAX_BURST_LENGTH 16, PHASE 0.0, CLK_DOMAIN xdma_hbm_xdma_0_0_axi_aclk, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0" *) input [32:0]AXI_01_ARADDR;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_01_RT ARBURST" *) input [1:0]AXI_01_ARBURST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_01_RT ARID" *) input [5:0]AXI_01_ARID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_01_RT ARLEN" *) input [3:0]AXI_01_ARLEN;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_01_RT ARSIZE" *) input [2:0]AXI_01_ARSIZE;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_01_RT ARVALID" *) input AXI_01_ARVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_01_RT AWADDR" *) input [32:0]AXI_01_AWADDR;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_01_RT AWBURST" *) input [1:0]AXI_01_AWBURST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_01_RT AWID" *) input [5:0]AXI_01_AWID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_01_RT AWLEN" *) input [3:0]AXI_01_AWLEN;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_01_RT AWSIZE" *) input [2:0]AXI_01_AWSIZE;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_01_RT AWVALID" *) input AXI_01_AWVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_01_RT RREADY" *) input AXI_01_RREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_01_RT BREADY" *) input AXI_01_BREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_01_RT WDATA" *) input [255:0]AXI_01_WDATA;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_01_RT WLAST" *) input AXI_01_WLAST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_01_RT WSTRB" *) input [31:0]AXI_01_WSTRB;
  input [31:0]AXI_01_WDATA_PARITY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_01_RT WVALID" *) input AXI_01_WVALID;
  (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 ACLK_02_RT CLK" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME ACLK_02_RT, ASSOCIATED_BUSIF SAXI_02_RT, FREQ_HZ 250000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN xdma_hbm_xdma_0_0_axi_aclk, ASSOCIATED_RESET AXI_02_ARESET_N, INSERT_VIP 0" *) input AXI_02_ACLK /* synthesis syn_isclock = 1 */;
  (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 ARST_02_N RST" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME ARST_02_N, POLARITY ACTIVE_LOW, INSERT_VIP 0" *) input AXI_02_ARESET_N;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_02_RT ARADDR" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME SAXI_02_RT, DATA_WIDTH 256, PROTOCOL AXI3, FREQ_HZ 250000000, ID_WIDTH 6, ADDR_WIDTH 33, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 1, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 1, NUM_READ_OUTSTANDING 2, NUM_WRITE_OUTSTANDING 2, MAX_BURST_LENGTH 16, PHASE 0.0, CLK_DOMAIN xdma_hbm_xdma_0_0_axi_aclk, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0" *) input [32:0]AXI_02_ARADDR;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_02_RT ARBURST" *) input [1:0]AXI_02_ARBURST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_02_RT ARID" *) input [5:0]AXI_02_ARID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_02_RT ARLEN" *) input [3:0]AXI_02_ARLEN;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_02_RT ARSIZE" *) input [2:0]AXI_02_ARSIZE;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_02_RT ARVALID" *) input AXI_02_ARVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_02_RT AWADDR" *) input [32:0]AXI_02_AWADDR;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_02_RT AWBURST" *) input [1:0]AXI_02_AWBURST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_02_RT AWID" *) input [5:0]AXI_02_AWID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_02_RT AWLEN" *) input [3:0]AXI_02_AWLEN;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_02_RT AWSIZE" *) input [2:0]AXI_02_AWSIZE;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_02_RT AWVALID" *) input AXI_02_AWVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_02_RT RREADY" *) input AXI_02_RREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_02_RT BREADY" *) input AXI_02_BREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_02_RT WDATA" *) input [255:0]AXI_02_WDATA;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_02_RT WLAST" *) input AXI_02_WLAST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_02_RT WSTRB" *) input [31:0]AXI_02_WSTRB;
  input [31:0]AXI_02_WDATA_PARITY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_02_RT WVALID" *) input AXI_02_WVALID;
  (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 ACLK_03_RT CLK" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME ACLK_03_RT, ASSOCIATED_BUSIF SAXI_03_RT, FREQ_HZ 250000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN xdma_hbm_xdma_0_0_axi_aclk, ASSOCIATED_RESET AXI_03_ARESET_N, INSERT_VIP 0" *) input AXI_03_ACLK /* synthesis syn_isclock = 1 */;
  (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 ARST_03_N RST" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME ARST_03_N, POLARITY ACTIVE_LOW, INSERT_VIP 0" *) input AXI_03_ARESET_N;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_03_RT ARADDR" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME SAXI_03_RT, DATA_WIDTH 256, PROTOCOL AXI3, FREQ_HZ 250000000, ID_WIDTH 6, ADDR_WIDTH 33, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 1, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 1, NUM_READ_OUTSTANDING 2, NUM_WRITE_OUTSTANDING 2, MAX_BURST_LENGTH 16, PHASE 0.0, CLK_DOMAIN xdma_hbm_xdma_0_0_axi_aclk, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0" *) input [32:0]AXI_03_ARADDR;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_03_RT ARBURST" *) input [1:0]AXI_03_ARBURST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_03_RT ARID" *) input [5:0]AXI_03_ARID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_03_RT ARLEN" *) input [3:0]AXI_03_ARLEN;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_03_RT ARSIZE" *) input [2:0]AXI_03_ARSIZE;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_03_RT ARVALID" *) input AXI_03_ARVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_03_RT AWADDR" *) input [32:0]AXI_03_AWADDR;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_03_RT AWBURST" *) input [1:0]AXI_03_AWBURST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_03_RT AWID" *) input [5:0]AXI_03_AWID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_03_RT AWLEN" *) input [3:0]AXI_03_AWLEN;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_03_RT AWSIZE" *) input [2:0]AXI_03_AWSIZE;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_03_RT AWVALID" *) input AXI_03_AWVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_03_RT RREADY" *) input AXI_03_RREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_03_RT BREADY" *) input AXI_03_BREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_03_RT WDATA" *) input [255:0]AXI_03_WDATA;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_03_RT WLAST" *) input AXI_03_WLAST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_03_RT WSTRB" *) input [31:0]AXI_03_WSTRB;
  input [31:0]AXI_03_WDATA_PARITY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_03_RT WVALID" *) input AXI_03_WVALID;
  (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 ACLK_04_RT CLK" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME ACLK_04_RT, ASSOCIATED_BUSIF SAXI_04_RT, FREQ_HZ 250000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN xdma_hbm_xdma_0_0_axi_aclk, ASSOCIATED_RESET AXI_04_ARESET_N, INSERT_VIP 0" *) input AXI_04_ACLK /* synthesis syn_isclock = 1 */;
  (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 ARST_04_N RST" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME ARST_04_N, POLARITY ACTIVE_LOW, INSERT_VIP 0" *) input AXI_04_ARESET_N;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_04_RT ARADDR" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME SAXI_04_RT, DATA_WIDTH 256, PROTOCOL AXI3, FREQ_HZ 250000000, ID_WIDTH 6, ADDR_WIDTH 33, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 1, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 1, NUM_READ_OUTSTANDING 2, NUM_WRITE_OUTSTANDING 2, MAX_BURST_LENGTH 16, PHASE 0.0, CLK_DOMAIN xdma_hbm_xdma_0_0_axi_aclk, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0" *) input [32:0]AXI_04_ARADDR;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_04_RT ARBURST" *) input [1:0]AXI_04_ARBURST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_04_RT ARID" *) input [5:0]AXI_04_ARID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_04_RT ARLEN" *) input [3:0]AXI_04_ARLEN;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_04_RT ARSIZE" *) input [2:0]AXI_04_ARSIZE;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_04_RT ARVALID" *) input AXI_04_ARVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_04_RT AWADDR" *) input [32:0]AXI_04_AWADDR;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_04_RT AWBURST" *) input [1:0]AXI_04_AWBURST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_04_RT AWID" *) input [5:0]AXI_04_AWID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_04_RT AWLEN" *) input [3:0]AXI_04_AWLEN;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_04_RT AWSIZE" *) input [2:0]AXI_04_AWSIZE;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_04_RT AWVALID" *) input AXI_04_AWVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_04_RT RREADY" *) input AXI_04_RREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_04_RT BREADY" *) input AXI_04_BREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_04_RT WDATA" *) input [255:0]AXI_04_WDATA;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_04_RT WLAST" *) input AXI_04_WLAST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_04_RT WSTRB" *) input [31:0]AXI_04_WSTRB;
  input [31:0]AXI_04_WDATA_PARITY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_04_RT WVALID" *) input AXI_04_WVALID;
  (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 ACLK_05_RT CLK" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME ACLK_05_RT, ASSOCIATED_BUSIF SAXI_05_RT, FREQ_HZ 250000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN xdma_hbm_xdma_0_0_axi_aclk, ASSOCIATED_RESET AXI_05_ARESET_N, INSERT_VIP 0" *) input AXI_05_ACLK /* synthesis syn_isclock = 1 */;
  (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 ARST_05_N RST" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME ARST_05_N, POLARITY ACTIVE_LOW, INSERT_VIP 0" *) input AXI_05_ARESET_N;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_05_RT ARADDR" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME SAXI_05_RT, DATA_WIDTH 256, PROTOCOL AXI3, FREQ_HZ 250000000, ID_WIDTH 6, ADDR_WIDTH 33, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 1, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 1, NUM_READ_OUTSTANDING 2, NUM_WRITE_OUTSTANDING 2, MAX_BURST_LENGTH 16, PHASE 0.0, CLK_DOMAIN xdma_hbm_xdma_0_0_axi_aclk, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0" *) input [32:0]AXI_05_ARADDR;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_05_RT ARBURST" *) input [1:0]AXI_05_ARBURST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_05_RT ARID" *) input [5:0]AXI_05_ARID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_05_RT ARLEN" *) input [3:0]AXI_05_ARLEN;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_05_RT ARSIZE" *) input [2:0]AXI_05_ARSIZE;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_05_RT ARVALID" *) input AXI_05_ARVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_05_RT AWADDR" *) input [32:0]AXI_05_AWADDR;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_05_RT AWBURST" *) input [1:0]AXI_05_AWBURST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_05_RT AWID" *) input [5:0]AXI_05_AWID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_05_RT AWLEN" *) input [3:0]AXI_05_AWLEN;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_05_RT AWSIZE" *) input [2:0]AXI_05_AWSIZE;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_05_RT AWVALID" *) input AXI_05_AWVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_05_RT RREADY" *) input AXI_05_RREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_05_RT BREADY" *) input AXI_05_BREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_05_RT WDATA" *) input [255:0]AXI_05_WDATA;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_05_RT WLAST" *) input AXI_05_WLAST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_05_RT WSTRB" *) input [31:0]AXI_05_WSTRB;
  input [31:0]AXI_05_WDATA_PARITY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_05_RT WVALID" *) input AXI_05_WVALID;
  (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 ACLK_06_RT CLK" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME ACLK_06_RT, ASSOCIATED_BUSIF SAXI_06_RT, FREQ_HZ 250000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN xdma_hbm_xdma_0_0_axi_aclk, ASSOCIATED_RESET AXI_06_ARESET_N, INSERT_VIP 0" *) input AXI_06_ACLK /* synthesis syn_isclock = 1 */;
  (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 ARST_06_N RST" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME ARST_06_N, POLARITY ACTIVE_LOW, INSERT_VIP 0" *) input AXI_06_ARESET_N;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_06_RT ARADDR" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME SAXI_06_RT, DATA_WIDTH 256, PROTOCOL AXI3, FREQ_HZ 250000000, ID_WIDTH 6, ADDR_WIDTH 33, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 1, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 1, NUM_READ_OUTSTANDING 2, NUM_WRITE_OUTSTANDING 2, MAX_BURST_LENGTH 16, PHASE 0.0, CLK_DOMAIN xdma_hbm_xdma_0_0_axi_aclk, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0" *) input [32:0]AXI_06_ARADDR;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_06_RT ARBURST" *) input [1:0]AXI_06_ARBURST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_06_RT ARID" *) input [5:0]AXI_06_ARID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_06_RT ARLEN" *) input [3:0]AXI_06_ARLEN;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_06_RT ARSIZE" *) input [2:0]AXI_06_ARSIZE;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_06_RT ARVALID" *) input AXI_06_ARVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_06_RT AWADDR" *) input [32:0]AXI_06_AWADDR;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_06_RT AWBURST" *) input [1:0]AXI_06_AWBURST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_06_RT AWID" *) input [5:0]AXI_06_AWID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_06_RT AWLEN" *) input [3:0]AXI_06_AWLEN;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_06_RT AWSIZE" *) input [2:0]AXI_06_AWSIZE;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_06_RT AWVALID" *) input AXI_06_AWVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_06_RT RREADY" *) input AXI_06_RREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_06_RT BREADY" *) input AXI_06_BREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_06_RT WDATA" *) input [255:0]AXI_06_WDATA;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_06_RT WLAST" *) input AXI_06_WLAST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_06_RT WSTRB" *) input [31:0]AXI_06_WSTRB;
  input [31:0]AXI_06_WDATA_PARITY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_06_RT WVALID" *) input AXI_06_WVALID;
  (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 ACLK_07_RT CLK" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME ACLK_07_RT, ASSOCIATED_BUSIF SAXI_07_RT, FREQ_HZ 250000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN xdma_hbm_xdma_0_0_axi_aclk, ASSOCIATED_RESET AXI_07_ARESET_N, INSERT_VIP 0" *) input AXI_07_ACLK /* synthesis syn_isclock = 1 */;
  (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 ARST_07_N RST" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME ARST_07_N, POLARITY ACTIVE_LOW, INSERT_VIP 0" *) input AXI_07_ARESET_N;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_07_RT ARADDR" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME SAXI_07_RT, DATA_WIDTH 256, PROTOCOL AXI3, FREQ_HZ 250000000, ID_WIDTH 6, ADDR_WIDTH 33, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 1, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 1, NUM_READ_OUTSTANDING 2, NUM_WRITE_OUTSTANDING 2, MAX_BURST_LENGTH 16, PHASE 0.0, CLK_DOMAIN xdma_hbm_xdma_0_0_axi_aclk, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0" *) input [32:0]AXI_07_ARADDR;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_07_RT ARBURST" *) input [1:0]AXI_07_ARBURST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_07_RT ARID" *) input [5:0]AXI_07_ARID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_07_RT ARLEN" *) input [3:0]AXI_07_ARLEN;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_07_RT ARSIZE" *) input [2:0]AXI_07_ARSIZE;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_07_RT ARVALID" *) input AXI_07_ARVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_07_RT AWADDR" *) input [32:0]AXI_07_AWADDR;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_07_RT AWBURST" *) input [1:0]AXI_07_AWBURST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_07_RT AWID" *) input [5:0]AXI_07_AWID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_07_RT AWLEN" *) input [3:0]AXI_07_AWLEN;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_07_RT AWSIZE" *) input [2:0]AXI_07_AWSIZE;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_07_RT AWVALID" *) input AXI_07_AWVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_07_RT RREADY" *) input AXI_07_RREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_07_RT BREADY" *) input AXI_07_BREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_07_RT WDATA" *) input [255:0]AXI_07_WDATA;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_07_RT WLAST" *) input AXI_07_WLAST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_07_RT WSTRB" *) input [31:0]AXI_07_WSTRB;
  input [31:0]AXI_07_WDATA_PARITY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_07_RT WVALID" *) input AXI_07_WVALID;
  (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 ACLK_08_RT CLK" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME ACLK_08_RT, ASSOCIATED_BUSIF SAXI_08_RT, FREQ_HZ 250000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN xdma_hbm_xdma_0_0_axi_aclk, ASSOCIATED_RESET AXI_08_ARESET_N, INSERT_VIP 0" *) input AXI_08_ACLK /* synthesis syn_isclock = 1 */;
  (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 ARST_08_N RST" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME ARST_08_N, POLARITY ACTIVE_LOW, INSERT_VIP 0" *) input AXI_08_ARESET_N;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_08_RT ARADDR" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME SAXI_08_RT, DATA_WIDTH 256, PROTOCOL AXI3, FREQ_HZ 250000000, ID_WIDTH 6, ADDR_WIDTH 33, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 1, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 1, NUM_READ_OUTSTANDING 2, NUM_WRITE_OUTSTANDING 2, MAX_BURST_LENGTH 16, PHASE 0.0, CLK_DOMAIN xdma_hbm_xdma_0_0_axi_aclk, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0" *) input [32:0]AXI_08_ARADDR;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_08_RT ARBURST" *) input [1:0]AXI_08_ARBURST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_08_RT ARID" *) input [5:0]AXI_08_ARID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_08_RT ARLEN" *) input [3:0]AXI_08_ARLEN;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_08_RT ARSIZE" *) input [2:0]AXI_08_ARSIZE;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_08_RT ARVALID" *) input AXI_08_ARVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_08_RT AWADDR" *) input [32:0]AXI_08_AWADDR;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_08_RT AWBURST" *) input [1:0]AXI_08_AWBURST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_08_RT AWID" *) input [5:0]AXI_08_AWID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_08_RT AWLEN" *) input [3:0]AXI_08_AWLEN;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_08_RT AWSIZE" *) input [2:0]AXI_08_AWSIZE;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_08_RT AWVALID" *) input AXI_08_AWVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_08_RT RREADY" *) input AXI_08_RREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_08_RT BREADY" *) input AXI_08_BREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_08_RT WDATA" *) input [255:0]AXI_08_WDATA;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_08_RT WLAST" *) input AXI_08_WLAST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_08_RT WSTRB" *) input [31:0]AXI_08_WSTRB;
  input [31:0]AXI_08_WDATA_PARITY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_08_RT WVALID" *) input AXI_08_WVALID;
  (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 ACLK_09_RT CLK" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME ACLK_09_RT, ASSOCIATED_BUSIF SAXI_09_RT, FREQ_HZ 250000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN xdma_hbm_xdma_0_0_axi_aclk, ASSOCIATED_RESET AXI_09_ARESET_N, INSERT_VIP 0" *) input AXI_09_ACLK /* synthesis syn_isclock = 1 */;
  (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 ARST_09_N RST" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME ARST_09_N, POLARITY ACTIVE_LOW, INSERT_VIP 0" *) input AXI_09_ARESET_N;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_09_RT ARADDR" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME SAXI_09_RT, DATA_WIDTH 256, PROTOCOL AXI3, FREQ_HZ 250000000, ID_WIDTH 6, ADDR_WIDTH 33, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 1, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 1, NUM_READ_OUTSTANDING 2, NUM_WRITE_OUTSTANDING 2, MAX_BURST_LENGTH 16, PHASE 0.0, CLK_DOMAIN xdma_hbm_xdma_0_0_axi_aclk, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0" *) input [32:0]AXI_09_ARADDR;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_09_RT ARBURST" *) input [1:0]AXI_09_ARBURST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_09_RT ARID" *) input [5:0]AXI_09_ARID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_09_RT ARLEN" *) input [3:0]AXI_09_ARLEN;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_09_RT ARSIZE" *) input [2:0]AXI_09_ARSIZE;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_09_RT ARVALID" *) input AXI_09_ARVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_09_RT AWADDR" *) input [32:0]AXI_09_AWADDR;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_09_RT AWBURST" *) input [1:0]AXI_09_AWBURST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_09_RT AWID" *) input [5:0]AXI_09_AWID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_09_RT AWLEN" *) input [3:0]AXI_09_AWLEN;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_09_RT AWSIZE" *) input [2:0]AXI_09_AWSIZE;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_09_RT AWVALID" *) input AXI_09_AWVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_09_RT RREADY" *) input AXI_09_RREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_09_RT BREADY" *) input AXI_09_BREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_09_RT WDATA" *) input [255:0]AXI_09_WDATA;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_09_RT WLAST" *) input AXI_09_WLAST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_09_RT WSTRB" *) input [31:0]AXI_09_WSTRB;
  input [31:0]AXI_09_WDATA_PARITY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_09_RT WVALID" *) input AXI_09_WVALID;
  (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 ACLK_10_RT CLK" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME ACLK_10_RT, ASSOCIATED_BUSIF SAXI_10_RT, FREQ_HZ 250000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN xdma_hbm_xdma_0_0_axi_aclk, ASSOCIATED_RESET AXI_10_ARESET_N, INSERT_VIP 0" *) input AXI_10_ACLK /* synthesis syn_isclock = 1 */;
  (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 ARST_10_N RST" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME ARST_10_N, POLARITY ACTIVE_LOW, INSERT_VIP 0" *) input AXI_10_ARESET_N;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_10_RT ARADDR" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME SAXI_10_RT, DATA_WIDTH 256, PROTOCOL AXI3, FREQ_HZ 250000000, ID_WIDTH 6, ADDR_WIDTH 33, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 1, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 1, NUM_READ_OUTSTANDING 2, NUM_WRITE_OUTSTANDING 2, MAX_BURST_LENGTH 16, PHASE 0.0, CLK_DOMAIN xdma_hbm_xdma_0_0_axi_aclk, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0" *) input [32:0]AXI_10_ARADDR;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_10_RT ARBURST" *) input [1:0]AXI_10_ARBURST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_10_RT ARID" *) input [5:0]AXI_10_ARID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_10_RT ARLEN" *) input [3:0]AXI_10_ARLEN;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_10_RT ARSIZE" *) input [2:0]AXI_10_ARSIZE;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_10_RT ARVALID" *) input AXI_10_ARVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_10_RT AWADDR" *) input [32:0]AXI_10_AWADDR;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_10_RT AWBURST" *) input [1:0]AXI_10_AWBURST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_10_RT AWID" *) input [5:0]AXI_10_AWID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_10_RT AWLEN" *) input [3:0]AXI_10_AWLEN;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_10_RT AWSIZE" *) input [2:0]AXI_10_AWSIZE;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_10_RT AWVALID" *) input AXI_10_AWVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_10_RT RREADY" *) input AXI_10_RREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_10_RT BREADY" *) input AXI_10_BREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_10_RT WDATA" *) input [255:0]AXI_10_WDATA;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_10_RT WLAST" *) input AXI_10_WLAST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_10_RT WSTRB" *) input [31:0]AXI_10_WSTRB;
  input [31:0]AXI_10_WDATA_PARITY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_10_RT WVALID" *) input AXI_10_WVALID;
  (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 ACLK_11_RT CLK" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME ACLK_11_RT, ASSOCIATED_BUSIF SAXI_11_RT, FREQ_HZ 250000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN xdma_hbm_xdma_0_0_axi_aclk, ASSOCIATED_RESET AXI_11_ARESET_N, INSERT_VIP 0" *) input AXI_11_ACLK /* synthesis syn_isclock = 1 */;
  (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 ARST_11_N RST" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME ARST_11_N, POLARITY ACTIVE_LOW, INSERT_VIP 0" *) input AXI_11_ARESET_N;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_11_RT ARADDR" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME SAXI_11_RT, DATA_WIDTH 256, PROTOCOL AXI3, FREQ_HZ 250000000, ID_WIDTH 6, ADDR_WIDTH 33, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 1, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 1, NUM_READ_OUTSTANDING 2, NUM_WRITE_OUTSTANDING 2, MAX_BURST_LENGTH 16, PHASE 0.0, CLK_DOMAIN xdma_hbm_xdma_0_0_axi_aclk, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0" *) input [32:0]AXI_11_ARADDR;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_11_RT ARBURST" *) input [1:0]AXI_11_ARBURST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_11_RT ARID" *) input [5:0]AXI_11_ARID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_11_RT ARLEN" *) input [3:0]AXI_11_ARLEN;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_11_RT ARSIZE" *) input [2:0]AXI_11_ARSIZE;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_11_RT ARVALID" *) input AXI_11_ARVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_11_RT AWADDR" *) input [32:0]AXI_11_AWADDR;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_11_RT AWBURST" *) input [1:0]AXI_11_AWBURST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_11_RT AWID" *) input [5:0]AXI_11_AWID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_11_RT AWLEN" *) input [3:0]AXI_11_AWLEN;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_11_RT AWSIZE" *) input [2:0]AXI_11_AWSIZE;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_11_RT AWVALID" *) input AXI_11_AWVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_11_RT RREADY" *) input AXI_11_RREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_11_RT BREADY" *) input AXI_11_BREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_11_RT WDATA" *) input [255:0]AXI_11_WDATA;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_11_RT WLAST" *) input AXI_11_WLAST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_11_RT WSTRB" *) input [31:0]AXI_11_WSTRB;
  input [31:0]AXI_11_WDATA_PARITY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_11_RT WVALID" *) input AXI_11_WVALID;
  (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 ACLK_12_RT CLK" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME ACLK_12_RT, ASSOCIATED_BUSIF SAXI_12_RT, FREQ_HZ 250000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN xdma_hbm_xdma_0_0_axi_aclk, ASSOCIATED_RESET AXI_12_ARESET_N, INSERT_VIP 0" *) input AXI_12_ACLK /* synthesis syn_isclock = 1 */;
  (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 ARST_12_N RST" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME ARST_12_N, POLARITY ACTIVE_LOW, INSERT_VIP 0" *) input AXI_12_ARESET_N;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_12_RT ARADDR" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME SAXI_12_RT, DATA_WIDTH 256, PROTOCOL AXI3, FREQ_HZ 250000000, ID_WIDTH 6, ADDR_WIDTH 33, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 1, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 1, NUM_READ_OUTSTANDING 2, NUM_WRITE_OUTSTANDING 2, MAX_BURST_LENGTH 16, PHASE 0.0, CLK_DOMAIN xdma_hbm_xdma_0_0_axi_aclk, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0" *) input [32:0]AXI_12_ARADDR;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_12_RT ARBURST" *) input [1:0]AXI_12_ARBURST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_12_RT ARID" *) input [5:0]AXI_12_ARID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_12_RT ARLEN" *) input [3:0]AXI_12_ARLEN;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_12_RT ARSIZE" *) input [2:0]AXI_12_ARSIZE;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_12_RT ARVALID" *) input AXI_12_ARVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_12_RT AWADDR" *) input [32:0]AXI_12_AWADDR;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_12_RT AWBURST" *) input [1:0]AXI_12_AWBURST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_12_RT AWID" *) input [5:0]AXI_12_AWID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_12_RT AWLEN" *) input [3:0]AXI_12_AWLEN;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_12_RT AWSIZE" *) input [2:0]AXI_12_AWSIZE;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_12_RT AWVALID" *) input AXI_12_AWVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_12_RT RREADY" *) input AXI_12_RREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_12_RT BREADY" *) input AXI_12_BREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_12_RT WDATA" *) input [255:0]AXI_12_WDATA;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_12_RT WLAST" *) input AXI_12_WLAST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_12_RT WSTRB" *) input [31:0]AXI_12_WSTRB;
  input [31:0]AXI_12_WDATA_PARITY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_12_RT WVALID" *) input AXI_12_WVALID;
  (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 ACLK_13_RT CLK" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME ACLK_13_RT, ASSOCIATED_BUSIF SAXI_13_RT, FREQ_HZ 250000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN xdma_hbm_xdma_0_0_axi_aclk, ASSOCIATED_RESET AXI_13_ARESET_N, INSERT_VIP 0" *) input AXI_13_ACLK /* synthesis syn_isclock = 1 */;
  (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 ARST_13_N RST" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME ARST_13_N, POLARITY ACTIVE_LOW, INSERT_VIP 0" *) input AXI_13_ARESET_N;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_13_RT ARADDR" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME SAXI_13_RT, DATA_WIDTH 256, PROTOCOL AXI3, FREQ_HZ 250000000, ID_WIDTH 6, ADDR_WIDTH 33, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 1, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 1, NUM_READ_OUTSTANDING 2, NUM_WRITE_OUTSTANDING 2, MAX_BURST_LENGTH 16, PHASE 0.0, CLK_DOMAIN xdma_hbm_xdma_0_0_axi_aclk, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0" *) input [32:0]AXI_13_ARADDR;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_13_RT ARBURST" *) input [1:0]AXI_13_ARBURST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_13_RT ARID" *) input [5:0]AXI_13_ARID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_13_RT ARLEN" *) input [3:0]AXI_13_ARLEN;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_13_RT ARSIZE" *) input [2:0]AXI_13_ARSIZE;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_13_RT ARVALID" *) input AXI_13_ARVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_13_RT AWADDR" *) input [32:0]AXI_13_AWADDR;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_13_RT AWBURST" *) input [1:0]AXI_13_AWBURST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_13_RT AWID" *) input [5:0]AXI_13_AWID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_13_RT AWLEN" *) input [3:0]AXI_13_AWLEN;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_13_RT AWSIZE" *) input [2:0]AXI_13_AWSIZE;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_13_RT AWVALID" *) input AXI_13_AWVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_13_RT RREADY" *) input AXI_13_RREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_13_RT BREADY" *) input AXI_13_BREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_13_RT WDATA" *) input [255:0]AXI_13_WDATA;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_13_RT WLAST" *) input AXI_13_WLAST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_13_RT WSTRB" *) input [31:0]AXI_13_WSTRB;
  input [31:0]AXI_13_WDATA_PARITY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_13_RT WVALID" *) input AXI_13_WVALID;
  (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 ACLK_14_RT CLK" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME ACLK_14_RT, ASSOCIATED_BUSIF SAXI_14_RT, FREQ_HZ 250000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN xdma_hbm_xdma_0_0_axi_aclk, ASSOCIATED_RESET AXI_14_ARESET_N, INSERT_VIP 0" *) input AXI_14_ACLK /* synthesis syn_isclock = 1 */;
  (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 ARST_14_N RST" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME ARST_14_N, POLARITY ACTIVE_LOW, INSERT_VIP 0" *) input AXI_14_ARESET_N;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_14_RT ARADDR" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME SAXI_14_RT, DATA_WIDTH 256, PROTOCOL AXI3, FREQ_HZ 250000000, ID_WIDTH 6, ADDR_WIDTH 33, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 1, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 1, NUM_READ_OUTSTANDING 2, NUM_WRITE_OUTSTANDING 2, MAX_BURST_LENGTH 16, PHASE 0.0, CLK_DOMAIN xdma_hbm_xdma_0_0_axi_aclk, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0" *) input [32:0]AXI_14_ARADDR;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_14_RT ARBURST" *) input [1:0]AXI_14_ARBURST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_14_RT ARID" *) input [5:0]AXI_14_ARID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_14_RT ARLEN" *) input [3:0]AXI_14_ARLEN;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_14_RT ARSIZE" *) input [2:0]AXI_14_ARSIZE;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_14_RT ARVALID" *) input AXI_14_ARVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_14_RT AWADDR" *) input [32:0]AXI_14_AWADDR;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_14_RT AWBURST" *) input [1:0]AXI_14_AWBURST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_14_RT AWID" *) input [5:0]AXI_14_AWID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_14_RT AWLEN" *) input [3:0]AXI_14_AWLEN;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_14_RT AWSIZE" *) input [2:0]AXI_14_AWSIZE;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_14_RT AWVALID" *) input AXI_14_AWVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_14_RT RREADY" *) input AXI_14_RREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_14_RT BREADY" *) input AXI_14_BREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_14_RT WDATA" *) input [255:0]AXI_14_WDATA;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_14_RT WLAST" *) input AXI_14_WLAST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_14_RT WSTRB" *) input [31:0]AXI_14_WSTRB;
  input [31:0]AXI_14_WDATA_PARITY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_14_RT WVALID" *) input AXI_14_WVALID;
  (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 ACLK_15_RT CLK" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME ACLK_15_RT, ASSOCIATED_BUSIF SAXI_15_RT, FREQ_HZ 250000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN xdma_hbm_xdma_0_0_axi_aclk, ASSOCIATED_RESET AXI_15_ARESET_N, INSERT_VIP 0" *) input AXI_15_ACLK /* synthesis syn_isclock = 1 */;
  (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 ARST_15_N RST" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME ARST_15_N, POLARITY ACTIVE_LOW, INSERT_VIP 0" *) input AXI_15_ARESET_N;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_15_RT ARADDR" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME SAXI_15_RT, DATA_WIDTH 256, PROTOCOL AXI3, FREQ_HZ 250000000, ID_WIDTH 6, ADDR_WIDTH 33, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 1, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 1, NUM_READ_OUTSTANDING 2, NUM_WRITE_OUTSTANDING 2, MAX_BURST_LENGTH 16, PHASE 0.0, CLK_DOMAIN xdma_hbm_xdma_0_0_axi_aclk, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0" *) input [32:0]AXI_15_ARADDR;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_15_RT ARBURST" *) input [1:0]AXI_15_ARBURST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_15_RT ARID" *) input [5:0]AXI_15_ARID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_15_RT ARLEN" *) input [3:0]AXI_15_ARLEN;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_15_RT ARSIZE" *) input [2:0]AXI_15_ARSIZE;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_15_RT ARVALID" *) input AXI_15_ARVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_15_RT AWADDR" *) input [32:0]AXI_15_AWADDR;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_15_RT AWBURST" *) input [1:0]AXI_15_AWBURST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_15_RT AWID" *) input [5:0]AXI_15_AWID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_15_RT AWLEN" *) input [3:0]AXI_15_AWLEN;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_15_RT AWSIZE" *) input [2:0]AXI_15_AWSIZE;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_15_RT AWVALID" *) input AXI_15_AWVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_15_RT RREADY" *) input AXI_15_RREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_15_RT BREADY" *) input AXI_15_BREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_15_RT WDATA" *) input [255:0]AXI_15_WDATA;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_15_RT WLAST" *) input AXI_15_WLAST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_15_RT WSTRB" *) input [31:0]AXI_15_WSTRB;
  input [31:0]AXI_15_WDATA_PARITY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_15_RT WVALID" *) input AXI_15_WVALID;
  (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 PCLK_0 CLK" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME PCLK_0, ASSOCIATED_BUSIF SAPB_0, FREQ_HZ 100000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN xdma_hbm_clk_wiz_0_0_clk_out1, INSERT_VIP 0" *) input APB_0_PCLK /* synthesis syn_isclock = 1 */;
  (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 PRST_0_N RST" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME PRST_0_N, POLARITY ACTIVE_LOW, INSERT_VIP 0" *) input APB_0_PRESET_N;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_00_RT ARREADY" *) output AXI_00_ARREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_00_RT AWREADY" *) output AXI_00_AWREADY;
  output [31:0]AXI_00_RDATA_PARITY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_00_RT RDATA" *) output [255:0]AXI_00_RDATA;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_00_RT RID" *) output [5:0]AXI_00_RID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_00_RT RLAST" *) output AXI_00_RLAST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_00_RT RRESP" *) output [1:0]AXI_00_RRESP;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_00_RT RVALID" *) output AXI_00_RVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_00_RT WREADY" *) output AXI_00_WREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_00_RT BID" *) output [5:0]AXI_00_BID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_00_RT BRESP" *) output [1:0]AXI_00_BRESP;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_00_RT BVALID" *) output AXI_00_BVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_01_RT ARREADY" *) output AXI_01_ARREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_01_RT AWREADY" *) output AXI_01_AWREADY;
  output [31:0]AXI_01_RDATA_PARITY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_01_RT RDATA" *) output [255:0]AXI_01_RDATA;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_01_RT RID" *) output [5:0]AXI_01_RID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_01_RT RLAST" *) output AXI_01_RLAST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_01_RT RRESP" *) output [1:0]AXI_01_RRESP;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_01_RT RVALID" *) output AXI_01_RVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_01_RT WREADY" *) output AXI_01_WREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_01_RT BID" *) output [5:0]AXI_01_BID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_01_RT BRESP" *) output [1:0]AXI_01_BRESP;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_01_RT BVALID" *) output AXI_01_BVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_02_RT ARREADY" *) output AXI_02_ARREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_02_RT AWREADY" *) output AXI_02_AWREADY;
  output [31:0]AXI_02_RDATA_PARITY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_02_RT RDATA" *) output [255:0]AXI_02_RDATA;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_02_RT RID" *) output [5:0]AXI_02_RID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_02_RT RLAST" *) output AXI_02_RLAST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_02_RT RRESP" *) output [1:0]AXI_02_RRESP;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_02_RT RVALID" *) output AXI_02_RVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_02_RT WREADY" *) output AXI_02_WREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_02_RT BID" *) output [5:0]AXI_02_BID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_02_RT BRESP" *) output [1:0]AXI_02_BRESP;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_02_RT BVALID" *) output AXI_02_BVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_03_RT ARREADY" *) output AXI_03_ARREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_03_RT AWREADY" *) output AXI_03_AWREADY;
  output [31:0]AXI_03_RDATA_PARITY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_03_RT RDATA" *) output [255:0]AXI_03_RDATA;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_03_RT RID" *) output [5:0]AXI_03_RID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_03_RT RLAST" *) output AXI_03_RLAST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_03_RT RRESP" *) output [1:0]AXI_03_RRESP;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_03_RT RVALID" *) output AXI_03_RVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_03_RT WREADY" *) output AXI_03_WREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_03_RT BID" *) output [5:0]AXI_03_BID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_03_RT BRESP" *) output [1:0]AXI_03_BRESP;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_03_RT BVALID" *) output AXI_03_BVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_04_RT ARREADY" *) output AXI_04_ARREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_04_RT AWREADY" *) output AXI_04_AWREADY;
  output [31:0]AXI_04_RDATA_PARITY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_04_RT RDATA" *) output [255:0]AXI_04_RDATA;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_04_RT RID" *) output [5:0]AXI_04_RID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_04_RT RLAST" *) output AXI_04_RLAST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_04_RT RRESP" *) output [1:0]AXI_04_RRESP;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_04_RT RVALID" *) output AXI_04_RVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_04_RT WREADY" *) output AXI_04_WREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_04_RT BID" *) output [5:0]AXI_04_BID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_04_RT BRESP" *) output [1:0]AXI_04_BRESP;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_04_RT BVALID" *) output AXI_04_BVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_05_RT ARREADY" *) output AXI_05_ARREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_05_RT AWREADY" *) output AXI_05_AWREADY;
  output [31:0]AXI_05_RDATA_PARITY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_05_RT RDATA" *) output [255:0]AXI_05_RDATA;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_05_RT RID" *) output [5:0]AXI_05_RID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_05_RT RLAST" *) output AXI_05_RLAST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_05_RT RRESP" *) output [1:0]AXI_05_RRESP;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_05_RT RVALID" *) output AXI_05_RVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_05_RT WREADY" *) output AXI_05_WREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_05_RT BID" *) output [5:0]AXI_05_BID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_05_RT BRESP" *) output [1:0]AXI_05_BRESP;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_05_RT BVALID" *) output AXI_05_BVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_06_RT ARREADY" *) output AXI_06_ARREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_06_RT AWREADY" *) output AXI_06_AWREADY;
  output [31:0]AXI_06_RDATA_PARITY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_06_RT RDATA" *) output [255:0]AXI_06_RDATA;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_06_RT RID" *) output [5:0]AXI_06_RID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_06_RT RLAST" *) output AXI_06_RLAST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_06_RT RRESP" *) output [1:0]AXI_06_RRESP;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_06_RT RVALID" *) output AXI_06_RVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_06_RT WREADY" *) output AXI_06_WREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_06_RT BID" *) output [5:0]AXI_06_BID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_06_RT BRESP" *) output [1:0]AXI_06_BRESP;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_06_RT BVALID" *) output AXI_06_BVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_07_RT ARREADY" *) output AXI_07_ARREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_07_RT AWREADY" *) output AXI_07_AWREADY;
  output [31:0]AXI_07_RDATA_PARITY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_07_RT RDATA" *) output [255:0]AXI_07_RDATA;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_07_RT RID" *) output [5:0]AXI_07_RID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_07_RT RLAST" *) output AXI_07_RLAST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_07_RT RRESP" *) output [1:0]AXI_07_RRESP;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_07_RT RVALID" *) output AXI_07_RVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_07_RT WREADY" *) output AXI_07_WREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_07_RT BID" *) output [5:0]AXI_07_BID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_07_RT BRESP" *) output [1:0]AXI_07_BRESP;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_07_RT BVALID" *) output AXI_07_BVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_08_RT ARREADY" *) output AXI_08_ARREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_08_RT AWREADY" *) output AXI_08_AWREADY;
  output [31:0]AXI_08_RDATA_PARITY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_08_RT RDATA" *) output [255:0]AXI_08_RDATA;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_08_RT RID" *) output [5:0]AXI_08_RID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_08_RT RLAST" *) output AXI_08_RLAST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_08_RT RRESP" *) output [1:0]AXI_08_RRESP;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_08_RT RVALID" *) output AXI_08_RVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_08_RT WREADY" *) output AXI_08_WREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_08_RT BID" *) output [5:0]AXI_08_BID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_08_RT BRESP" *) output [1:0]AXI_08_BRESP;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_08_RT BVALID" *) output AXI_08_BVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_09_RT ARREADY" *) output AXI_09_ARREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_09_RT AWREADY" *) output AXI_09_AWREADY;
  output [31:0]AXI_09_RDATA_PARITY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_09_RT RDATA" *) output [255:0]AXI_09_RDATA;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_09_RT RID" *) output [5:0]AXI_09_RID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_09_RT RLAST" *) output AXI_09_RLAST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_09_RT RRESP" *) output [1:0]AXI_09_RRESP;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_09_RT RVALID" *) output AXI_09_RVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_09_RT WREADY" *) output AXI_09_WREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_09_RT BID" *) output [5:0]AXI_09_BID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_09_RT BRESP" *) output [1:0]AXI_09_BRESP;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_09_RT BVALID" *) output AXI_09_BVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_10_RT ARREADY" *) output AXI_10_ARREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_10_RT AWREADY" *) output AXI_10_AWREADY;
  output [31:0]AXI_10_RDATA_PARITY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_10_RT RDATA" *) output [255:0]AXI_10_RDATA;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_10_RT RID" *) output [5:0]AXI_10_RID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_10_RT RLAST" *) output AXI_10_RLAST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_10_RT RRESP" *) output [1:0]AXI_10_RRESP;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_10_RT RVALID" *) output AXI_10_RVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_10_RT WREADY" *) output AXI_10_WREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_10_RT BID" *) output [5:0]AXI_10_BID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_10_RT BRESP" *) output [1:0]AXI_10_BRESP;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_10_RT BVALID" *) output AXI_10_BVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_11_RT ARREADY" *) output AXI_11_ARREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_11_RT AWREADY" *) output AXI_11_AWREADY;
  output [31:0]AXI_11_RDATA_PARITY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_11_RT RDATA" *) output [255:0]AXI_11_RDATA;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_11_RT RID" *) output [5:0]AXI_11_RID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_11_RT RLAST" *) output AXI_11_RLAST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_11_RT RRESP" *) output [1:0]AXI_11_RRESP;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_11_RT RVALID" *) output AXI_11_RVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_11_RT WREADY" *) output AXI_11_WREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_11_RT BID" *) output [5:0]AXI_11_BID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_11_RT BRESP" *) output [1:0]AXI_11_BRESP;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_11_RT BVALID" *) output AXI_11_BVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_12_RT ARREADY" *) output AXI_12_ARREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_12_RT AWREADY" *) output AXI_12_AWREADY;
  output [31:0]AXI_12_RDATA_PARITY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_12_RT RDATA" *) output [255:0]AXI_12_RDATA;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_12_RT RID" *) output [5:0]AXI_12_RID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_12_RT RLAST" *) output AXI_12_RLAST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_12_RT RRESP" *) output [1:0]AXI_12_RRESP;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_12_RT RVALID" *) output AXI_12_RVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_12_RT WREADY" *) output AXI_12_WREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_12_RT BID" *) output [5:0]AXI_12_BID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_12_RT BRESP" *) output [1:0]AXI_12_BRESP;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_12_RT BVALID" *) output AXI_12_BVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_13_RT ARREADY" *) output AXI_13_ARREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_13_RT AWREADY" *) output AXI_13_AWREADY;
  output [31:0]AXI_13_RDATA_PARITY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_13_RT RDATA" *) output [255:0]AXI_13_RDATA;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_13_RT RID" *) output [5:0]AXI_13_RID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_13_RT RLAST" *) output AXI_13_RLAST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_13_RT RRESP" *) output [1:0]AXI_13_RRESP;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_13_RT RVALID" *) output AXI_13_RVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_13_RT WREADY" *) output AXI_13_WREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_13_RT BID" *) output [5:0]AXI_13_BID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_13_RT BRESP" *) output [1:0]AXI_13_BRESP;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_13_RT BVALID" *) output AXI_13_BVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_14_RT ARREADY" *) output AXI_14_ARREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_14_RT AWREADY" *) output AXI_14_AWREADY;
  output [31:0]AXI_14_RDATA_PARITY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_14_RT RDATA" *) output [255:0]AXI_14_RDATA;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_14_RT RID" *) output [5:0]AXI_14_RID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_14_RT RLAST" *) output AXI_14_RLAST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_14_RT RRESP" *) output [1:0]AXI_14_RRESP;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_14_RT RVALID" *) output AXI_14_RVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_14_RT WREADY" *) output AXI_14_WREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_14_RT BID" *) output [5:0]AXI_14_BID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_14_RT BRESP" *) output [1:0]AXI_14_BRESP;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_14_RT BVALID" *) output AXI_14_BVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_15_RT ARREADY" *) output AXI_15_ARREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_15_RT AWREADY" *) output AXI_15_AWREADY;
  output [31:0]AXI_15_RDATA_PARITY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_15_RT RDATA" *) output [255:0]AXI_15_RDATA;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_15_RT RID" *) output [5:0]AXI_15_RID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_15_RT RLAST" *) output AXI_15_RLAST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_15_RT RRESP" *) output [1:0]AXI_15_RRESP;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_15_RT RVALID" *) output AXI_15_RVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_15_RT WREADY" *) output AXI_15_WREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_15_RT BID" *) output [5:0]AXI_15_BID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_15_RT BRESP" *) output [1:0]AXI_15_BRESP;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_15_RT BVALID" *) output AXI_15_BVALID;
  output apb_complete_0;
  output DRAM_0_STAT_CATTRIP;
  output [6:0]DRAM_0_STAT_TEMP;
endmodule
